# DELETE  http://localhost:8080/pokemon/release/13
# Content-Type: application/json

# {
#     "username" : "oryan"
# }

PUT  http://localhost:8080/pokemon/catch/15
Content-Type: application/json

{
    "username" : "oryan"
}