DELETE  http://localhost:8080/pokemon/release/80
Content-Type: application/json
username: new

{
    "username" : "new"
}

# PUT  http://localhost:8080/pokemon/catch/100
# Content-Type: application/json
# username: new

# {
#     "username" : "new"
# }

# POST  http://localhost:8080/users/orbyan/info
# Content-Type: application/json

# {
#     "username" : "oryan"
# }

# GET  http://localhost:8080/pokemon/ditto


# {
# }